import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from "./components/searchBar/searchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="relative bg-black">
          <div className="absolute top-0 left-0 w-full h-full">
              <img
                  src="/background.png"
                  alt="background"
                  className="h-screen w-full object-cover"
              />
          </div>
          <div className="absolute top-0 left-0 w-full h-screen bg-linear-to-b from-green/10 to-green" />
          <div className='relative'>
            <SearchBar />
            {children}
          </div>
        </div>

      </body>
    </html>
  );
}
